// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using data_name;

namespace EF_core.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20180920181709_Createmain_noted1")]
    partial class Createmain_noted1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("harsha.Checklist", b =>
                {
                    b.Property<int>("checklist_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Checklists");

                    b.Property<int>("NoteId");

                    b.HasKey("checklist_Id");

                    b.HasIndex("NoteId");

                    b.ToTable("Ch1");
                });

            modelBuilder.Entity("harsha.Labels", b =>
                {
                    b.Property<int>("Label_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label");

                    b.Property<int>("NoteId");

                    b.HasKey("Label_Id");

                    b.HasIndex("NoteId");

                    b.ToTable("L1");
                });

            modelBuilder.Entity("harsha.Student", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Pinned");

                    b.Property<string>("Plaintext");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("NoteId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("harsha.Checklist", b =>
                {
                    b.HasOne("harsha.Student")
                        .WithMany("Many_values_ch")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("harsha.Labels", b =>
                {
                    b.HasOne("harsha.Student")
                        .WithMany("Many_values")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
